name: Hisse Takip Botu

on:
  schedule:
    # Her 15 dakikada bir çalıştır (Pazartesi-Cuma borsa saatleri için uygundur)
    - cron: '*/15 * * * *'
  workflow_dispatch: # Manuel tetikleme için (Telefondan çalıştırmak istersen bu lazım)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install yfinance requests

      - name: Kodu Çalıştır
        # Artık env kısmında TELEGRAM_TOKEN ve CHAT_ID'ye gerek yok!
        run: python hisse_takip.py
        env:
       
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

