name: Hisse Takip Botu

on:
  schedule:
    # Her 15 dakikada bir çalıştır (Cron formatı)
    - cron: '*/15 * * * *'
  workflow_dispatch: # Manuel çalıştırmak istersen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install yfinance requests

      - name: Kodu Çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python hisse_takip.py
